"""add schedules table

Revision ID: 0ee193be0991
Revises: d7a7b9c70a98
Create Date: 2026-09-18 00:59:24.779470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ee193be0991'
down_revision: Union[str, Sequence[str], None] = 'd7a7b9c70a98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_assignment_id', sa.Integer(), nullable=False),
    sa.Column('room', sa.String(length=50), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.Enum('PREVU', 'MODIFIE', 'ANNULE', name='schedule_status'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teacher_assignment_id'], ['teacher_assignments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_session_date'), 'schedules', ['session_date'], unique=False)
    op.create_index(op.f('ix_schedules_teacher_assignment_id'), 'schedules', ['teacher_assignment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedules_teacher_assignment_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_session_date'), table_name='schedules')
    op.drop_table('schedules')
    # ### end Alembic commands ###
