"""add lost_found_items and potential_matches tables

Revision ID: 74d0efdba866
Revises: a5f117233d1c
Create Date: 2026-09-18 01:46:04.466747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74d0efdba866'
down_revision: Union[str, Sequence[str], None] = 'a5f117233d1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lost_found_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.Enum('PERDU', 'TROUVE', name='item_type'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('item_date', sa.Date(), nullable=False),
    sa.Column('photo_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('OUVERT', 'RESOLU', 'FERME', name='item_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lost_found_items_item_date'), 'lost_found_items', ['item_date'], unique=False)
    op.create_index(op.f('ix_lost_found_items_item_type'), 'lost_found_items', ['item_type'], unique=False)
    op.create_index(op.f('ix_lost_found_items_user_id'), 'lost_found_items', ['user_id'], unique=False)
    op.create_table('potential_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lost_item_id', sa.Integer(), nullable=False),
    sa.Column('found_item_id', sa.Integer(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PROPOSEE', 'CONFIRMEE', 'REJETEE', name='match_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['found_item_id'], ['lost_found_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lost_item_id'], ['lost_found_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lost_item_id', 'found_item_id', name='uq_lost_found_pair')
    )
    op.create_index(op.f('ix_potential_matches_found_item_id'), 'potential_matches', ['found_item_id'], unique=False)
    op.create_index(op.f('ix_potential_matches_lost_item_id'), 'potential_matches', ['lost_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_potential_matches_lost_item_id'), table_name='potential_matches')
    op.drop_index(op.f('ix_potential_matches_found_item_id'), table_name='potential_matches')
    op.drop_table('potential_matches')
    op.drop_index(op.f('ix_lost_found_items_user_id'), table_name='lost_found_items')
    op.drop_index(op.f('ix_lost_found_items_item_type'), table_name='lost_found_items')
    op.drop_index(op.f('ix_lost_found_items_item_date'), table_name='lost_found_items')
    op.drop_table('lost_found_items')
    # ### end Alembic commands ###
