"""add absence_requests table

Revision ID: a5f117233d1c
Revises: 145046c20626
Create Date: 2026-09-18 01:32:43.730226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5f117233d1c'
down_revision: Union[str, Sequence[str], None] = '145046c20626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('absence_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('justificatif_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('EN_ATTENTE', 'ACCEPTEE', 'REFUSEE', name='absence_status'), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_absence_requests_schedule_id'), 'absence_requests', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_absence_requests_student_id'), 'absence_requests', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_absence_requests_student_id'), table_name='absence_requests')
    op.drop_index(op.f('ix_absence_requests_schedule_id'), table_name='absence_requests')
    op.drop_table('absence_requests')
    # ### end Alembic commands ###
